apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: app/v1
kind: StatefulSet
metadata:
  name: web-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-server
    spec:
      selector:
        matchLabels:
          app: web-server
      containers:
        - name: web-server
          image: eu.gcr.io/experimental-berlin/discourse
          command: ["/sbin/boot"]
          ports:
            - containerPort: 80
          env:
            - name: DISCOURSE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbUsername
            - name: DISCOURSE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbPassword
            - name: DISCOURSE_DB_HOST
              value: discourse-production.postgres.svc.cluster.local
            - name: DISCOURSE_DB_NAME
              value: discourse
            - name: DISCOURSE_REDIS_HOST
              value: redis
            - name: DISCOURSE_DEVELOPER_EMAILS
              value: admin@experimental.berlin
            - name: DISCOURSE_HOSTNAME
              value: discuss.experimental.berlin
            - name: DISCOURSE_SMTP_ADDRESS
              value: smtp.sendgrid.net
            - name: DISCOURSE_SMTP_PORT
              value: "2525"
            - name: DISCOURSE_SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: smtpUsername
            - name: DISCOURSE_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: smtpPassword
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          imagePullPolicy: Always
          volumeMounts:
          - name: discourse-storage
            mountPath: /shared
  volumeClaimTemplates:
  - metadata:
      name: discourse-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 10Gi
