apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-server
  sessionAffinity: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  serviceName: web-server
  selector:
    matchLabels:
      app: web-server
  replicas: 2
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: aknudsen/discourse
          command: ["/sbin/boot"]
          ports:
            - containerPort: 80
          env:
            - name: DISCOURSE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discourse
                  key: dbUsername
            - name: DISCOURSE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discourse
                  key: dbPassword
            - name: PGSSLMODE
              value: require
            - name: DISCOURSE_DB_HOST
              value: discourse-production.postgres.svc.cluster.local
            - name: DISCOURSE_DB_NAME
              value: discourse
            - name: DISCOURSE_REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: DISCOURSE_DEVELOPER_EMAILS
              value: admin@experimental.berlin
            - name: DISCOURSE_HOSTNAME
              value: discuss.experimental.berlin
            - name: DISCOURSE_SMTP_ADDRESS
              value: smtp.mandrillapp.com
            - name: DISCOURSE_SMTP_PORT
              value: "2525"
            - name: DISCOURSE_SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: discourse
                  key: smtpUsername
            - name: DISCOURSE_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discourse
                  key: smtpPassword
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          imagePullPolicy: Always
          volumeMounts:
          - name: discourse-storage
            mountPath: /shared
  volumeClaimTemplates:
  - metadata:
      name: discourse-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discourse-ingress
spec:
  rules:
  - host: discuss.experimental.berlin
    http:
      paths:
      - backend:
          serviceName: web-server
          servicePort: 80
  tls:
  - hosts:
    - discuss.experimental.berlin
